name: CICD workflow with azure

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        path: MiniProjetBooks

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.x  

    - name: Restore Dependencies
      run: dotnet restore
      working-directory: MiniProjetBooks/MiniProjetBooks

    - name: Building
      run: dotnet build --configuration Release
      working-directory: MiniProjetBooks/MiniProjetBooks

    - name: Tests
      run: dotnet test --configuration Release
      working-directory: MiniProjetBooks/MiniProjetBooks
      
    - name: Publish
      run: dotnet publish -c Release -o '$(build.artifactStagingDirectory)'
      
    - name: Deploy to Azure
      uses: Azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.IEA_BOOKS_WEB_APP }}
        publish-profile: ${{ secrets.IEABOOKS_PUBLISH_PROFILE }}
